//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Arbi5UI.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_MYArbiTYPE                  129
#define IDD_DIALOG_STRATEGY             129
#define IDD_DIALOG_DTAIL                130
#define IDD_DIALOG_MEETING_PAGE         130
#define IDD_DIALOG2                     134
#define IDD_DLG_HEX                     134
#define IDD_DIRTREEDIG                  137
#define IDI_ICON1                       153
#define IDI_ICON2                       154
#define IDI_ICON3                       155
#define IDD_MSGPage                     156
#define IDD_DIALOG_DTAIL_CN             157
#define IDD_DIALOG_HEX                  158
#define IDR_FILTER                      159
#define IDD_DIALOG_ADD_MEETING          161
#define IDD_MEETING_PAGE                163
#define IDI_ICON4                       171
#define IDI_ICON5                       172
#define IDI_ICON6                       173
#define IDB_BITMAP1                     174
#define IDI_ICON7                       175
#define IDI_ICON8                       176
#define IDB_BITMAP2                     177
#define IDB_BITMAP3                     178
#define IDB_BITMAP4                     179
#define IDD_DIALOG_MEINFO_PAGE          180
#define IDD_DIALOG_PERSONINFO_PAGE      181
#define IDD_DIALOG_TABLE_PAGE           182
#define IDD_DIALOG_DISCUSS_PAGE         183
#define IDD_DIALOG_VEDIO_PAGE           184
#define IDD_DIALOG_AUTH_INFO            185
#define IDD_DIALOG_LOG_DLG              186
#define IDD_DIALOG_QUERY_RECORD_DLG     187
#define IDD_DIALOG_INTENTIONPAIR        187
#define IDD_DIALOG_KEY_INFO_DLG         188
#define IDD_DIALOG_ARBI_LOG             188
#define IDD_DIALOG_KEY_TREE             189
#define IDD_DIALOG_STRATEGY_INFO        189
#define IDD_DIALOG_AUTH_MANAGE_DLG      190
#define IDD_DIALOG_SET_KEY              192
#define IDD_DIALOG_OPER_MANAGE          193
#define IDD_DIALOG_USER_LOAD            195
#define IDD_DIALOG_SET_AUTH_TCODE       197
#define IDD_DIALOG_QUERY_DLG            198
#define IDB_Toolbar                     199
#define IDD_DIALOG_LOG                  200
#define IDR_POP_MENU                    202
#define IDD_DIALOG_INTENTION            203
#define IDR_POP_INTENTION_MENU          203
#define IDD_DIALOG_EXCHANGE_RATE        204
#define IDD_DIALOG_DEAL_WARNING         205
#define IDD_DIALOG_USER_MANAGE          206
#define IDD_DIALOG_AUTH                 207
#define IDD_DIALOG1                     208
#define IDD_DIALOG_DATA_CURVE           209
#define IDD_DIALOG_STRATEGY_MORE        210
#define IDD_DIALOG_ARBI_LOG1            211
#define IDD_DIALOG_ARBI_REPORT          211
#define IDC_LIST1                       1000
#define IDC_LIST_PACKET                 1000
#define IDC_LIST_MEETING                1000
#define IDC_LIST_FILES                  1000
#define IDC_LIST_QUERY_RECORD           1000
#define IDC_LIST_AUTH_DATA              1000
#define IDC_LIST_AUTH                   1000
#define IDC_LIST_USER                   1000
#define IDC_Toolbar                     1000
#define IDC_LIST_INTENTION_PAIR         1000
#define IDC_EDIT1                       1001
#define IDC_LIST_UNLOCK_RECORD          1001
#define IDC_EDIT_AUTH_ACTIVE            1001
#define IDC_EDIT_NAME                   1001
#define IDC_EDIT_QUERY_KEY_ID           1001
#define IDC_EDIT_DIFF1                  1001
#define IDC_EDIT_DOLLAR_EXR             1001
#define IDC_EDIT_LOCAL_CODE             1001
#define IDC_EDIT_SUGAR                  1001
#define IDC_BUTTON1                     1002
#define IDC_BUTTON_DEC                  1002
#define IDC_LOCALVIDEO                  1002
#define IDC_BUTTON_SET_AUTH_TCODE       1002
#define IDC_BUTTON_SETLEVEL             1002
#define IDC_BUTTON_SET_NEW_TCODE        1002
#define IDC_EDIT_USER_CODE              1002
#define IDC_BUTTON_QUERY_ALL_UNLOCK_INFO 1002
#define IDC_BUTTON_ADD_INTENTION        1002
#define IDC_EDIT_DIFF2                  1002
#define IDC_EDIT_YEN_EXR                1002
#define IDC_EDIT20                      1002
#define IDC_EDIT_OLDPWD                 1002
#define IDC_EDIT_AUTH_CODE              1002
#define IDC_BUTTON2                     1003
#define IDC_BUTTON_MOD_AUTH             1003
#define IDC_BUTTON_ACTIVE               1003
#define IDC_BUTTON_LOAD                 1003
#define IDC_EDIT_TCODE                  1003
#define ID_EDIT_NAME                    1003
#define IDC_EDIT21                      1003
#define IDC_EDIT_NEWPWD                 1003
#define IDC_BUTTON3                     1004
#define IDC_BUTTON_DEL_AUTH             1004
#define IDC_BUTTON_SET_SYS_TIME         1004
#define ID_COM_CONCERN                  1004
#define IDC_EDIT22                      1004
#define IDC_EDIT_CONFIRM_PWD            1004
#define IDC_EDIT_STEP                   1004
#define IDC_BUTTON_SET_AUTHUNLOCK       1005
#define IDC_EDIT_CON_PWD                1005
#define IDC_EDIT_CONTRACT_OVERSEA       1005
#define IDC_MONTHCALENDAR1              1006
#define IDC_BUTTON_SET_UNLOCK_TIME      1006
#define ID_COM_OVERSEAS                 1006
#define IDC_EDIT_FIRST_VOL              1006
#define IDC_TREE1                       1007
#define IDC_TREE_MEETING                1007
#define IDC_BUTTON_DEL_DATA             1007
#define IDC_EDIT_CONTRACT_DOMESTIC      1007
#define IDC_COM_DOMESTIC                1008
#define IDC_EDIT_SECOND_VOL             1008
#define IDC_DATETIMEPICKER1             1009
#define IDC_EDIT_VOLUME_OVERSEA         1009
#define IDC_DATETIMEPICKER2             1010
#define IDC_EDIT_VOLUME_DOMESTIC        1010
#define IDC_STATIC_ST                   1011
#define IDC_DATETIMEPICKER3             1011
#define IDC_LIST_CONSTRIANT             1011
#define ID_COM_OVERSEAS3                1011
#define ID_COM_OVERSEAS_TYPE            1011
#define IDC_STATIC_ET                   1012
#define IDC_DATETIMEPICKER4             1012
#define ID_BUTTON_ADD                   1012
#define ID_BUTTON_OK                    1012
#define IDC_COMBO1                      1013
#define IDC_COMBO_TYPE                  1013
#define IDC_COMBO_CHECK                 1013
#define IDC_COMBO_KEY_WORKSTATE         1013
#define ID_BUTTON_DEL                   1013
#define IDC_COMBO_COMPARE1              1013
#define IDC_EDIT2                       1014
#define IDC_EDIT_KEY_ID                 1014
#define IDC_COMBO_KEY_LEVEL             1014
#define IDC_EDIT_LOG                    1014
#define IDC_BUTTON_STOP                 1014
#define IDC_COMBO_COMPARE2              1014
#define IDC_EDIT_SUGAR2                 1014
#define IDC_COMBO2                      1015
#define IDC_COMBO_TABLE                 1015
#define IDC_EDIT8                       1015
#define IDC_EDIT_KEY_CUR_STATE          1015
#define IDC_COMBO_CLEAR_TYPE            1015
#define IDC_EDIT_ADD_OVERSEA            1015
#define IDC_EDIT3                       1016
#define IDC_EDIT_PERSON                 1016
#define IDC_EDIT_ADD_DOMESTIC           1016
#define IDC_BUTTON_ADD                  1017
#define IDC_EDIT9                       1017
#define IDC_EDIT_CUR_AUTH_ID            1017
#define ID_COM_OVERSEAS2                1017
#define IDC_BUTTON_DEL                  1018
#define IDC_EDIT10                      1018
#define IDC_EDIT_KEY_WORK_STATE         1018
#define IDC_COM_DOMESTIC2               1018
#define IDC_BUTTON_MODIFY               1019
#define IDC_EDIT11                      1019
#define IDC_EDIT_KEY_DAYTIME            1019
#define IDC_EDIT_VOLUME_OVERSEA2        1019
#define IDC_EDIT12                      1020
#define IDC_EDIT_KEY_SCHANGE            1020
#define IDC_EDIT_VOLUME_DOMESTIC2       1020
#define IDC_STATIC_AG                   1021
#define IDC_EDIT13                      1021
#define IDC_EDIT_KEY_TCODE_CHANGE       1021
#define IDC_EDIT_ADD_OVERSEA2           1021
#define IDC_EDIT4                       1022
#define IDC_EDIT14                      1022
#define IDC_EDIT_CURKEYID               1022
#define IDC_EDIT_KEY_TYPE_CODE          1022
#define IDC_EDIT_LOCKID_SIT             1022
#define IDC_EDIT_ADD_DOMESTIC2          1022
#define IDC_EDIT5                       1023
#define IDC_EDIT15                      1023
#define IDC_EDIT_AUTH_TCODE             1023
#define IDC_EDIT_KEY_UNLOCKC            1023
#define IDC_EDIT_LOCKID                 1023
#define IDC_COM_DOMESTIC3               1023
#define IDC_COM_DOMESTIC_TYPE           1023
#define IDC_EDIT6                       1024
#define IDC_BUTTON_ADD_FILES            1024
#define IDC_EDIT16                      1024
#define IDC_EDIT_KEY_LOCKC              1024
#define IDC_EDIT_TIME_TYPE              1024
#define ID_COM_OVERSEAS_TYPE2           1024
#define IDC_EDIT7                       1025
#define IDC_BUTTON_DEL_FILE             1025
#define IDC_EDIT17                      1025
#define IDC_EDIT_KEY_POPEDOM_CODE       1025
#define IDC_EDIT_TIME_SIT               1025
#define IDC_COM_DOMESTIC_TYPE2          1025
#define IDC_STATIC_MEETING              1026
#define IDC_EDIT18                      1026
#define IDC_EDIT_MM                     1026
#define IDC_EDIT_MAX_POSITIONS          1026
#define IDC_LIST_MEETING_P              1027
#define IDC_EDIT19                      1027
#define IDC_EDIT_KEY_LEVEL_CODE         1027
#define IDC_EDIT_DD                     1027
#define ID_BUTTON_TURN_OVER             1027
#define IDC_EDIT_MAX_COUNT              1027
#define IDC_BUTTON_DEL_P                1028
#define IDC_EDIT_LEVEL                  1028
#define IDC_EDIT_MM2                    1028
#define IDC_BUTTON_START_VEDIO          1029
#define IDC_EDIT_DD2                    1029
#define IDC_LIST_RECORD_LIST            1030
#define IDC_EDIT_HH                     1030
#define IDC_BUTTON_SET                  1031
#define IDC_EDIT_MI                     1031
#define IDC_TREE_KEY                    1032
#define IDC_EDIT_HH2                    1032
#define IDC_BUTTON_ADD_AUTH             1033
#define IDC_EDIT_MI2                    1033
#define IDC_EDIT_COM                    1034
#define IDC_EDIT_TIMETYPE               1034
#define IDC_EDIT_BPS                    1035
#define IDC_EDIT_TIMESIT                1035
#define IDC_EDIT_STOP                   1036
#define IDC_EDIT_DATA                   1037
#define IDC_EDIT_AUTH_ADDR              1039
#define IDC_EDIT_AUTH_ID                1040
#define IDC_EDIT_AUTH_KEY               1041
#define IDC_EDIT_AUTH_KEY_TYPE          1042
#define IDC_EDIT_SECKEY_STATE           1043
#define IDC_EDIT_AUTH_STATE             1044
#define IDC_EDIT_TCODEMODE              1045
#define IDC_EDIT_TCODESTATE             1046
#define IDC_EDIT_KEY_KEY_ID             1047
#define IDC_EDIT_KEY_CHANGE             1048
#define IDC_EDIT_KEY_TYPE               1049
#define IDC_EDIT_KEY_LOCKCOUNT          1050
#define IDC_EDIT_KEY_WORKSTATE          1051
#define IDC_EDIT_KEY_TIME               1052
#define IDC_EDIT_KEY_TCODESTATE         1053
#define IDC_EDIT_KEY_POPEDOM            1054
#define IDC_EDIT_KEY_UNLKCOUNT          1055
#define IDC_COMBO_KEYID                 1056
#define IDC_STATIC_NOTE                 1057
#define IDC_COMBO_USER_P                1058
#define IDC_EDIT_USER                   1059
#define IDC_EDIT_PWD                    1060
#define IDC_STATIC_CURTIME              1061
#define IDC_EDIT_NEW_TCODE              1062
#define IDC_RICHEDIT_LOG                1063
#define IDC_RICHEDIT1                   1065
#define IDC_LIST_STRATEGY_INFO          1066
#define IDC_CHECK1                      1067
#define IDC_CHECK2                      1068
#define IDC_CHECK_EDIT_AND_START        1069
#define ID_PROSESS_FIRST_OK             1070
#define IDC_CHECK_FISH1                 1070
#define ID_ADD_SECOND_OK                1071
#define IDC_CHECK_FISH2                 1071
#define IDC_STATIC_WARNING              1072
#define IDC_RADIO1                      1073
#define IDC_RADIO2                      1074
#define IDC_CHECK_PING                  1076
#define ID_SHOWLEFTBAR                  32771
#define ID_BUTTON32772                  32772
#define ID_SHOWBOTTOMBAR                32773
#define ID_BUTTON_FIND                  32774
#define ID_BUTTON_BOX                   32775
#define ID_BUTTON_FILTER                32776
#define ID_SHOWRIGHTBAR                 32778
#define ID_MEET_ADD_AG                  32779
#define ID_ID_SYS_CONFIG                32779
#define ID_ADD_PERSON                   32780
#define ID_ADD_LOCK                     32780
#define ID_ID_ADD_LOCK                  32780
#define ID_ID_MEET_ADD_MEET             32781
#define ID_ID_USER_CONFIG               32781
#define ID_MEET_CONFIG                  32782
#define ID_KEY_CONFIG                   32782
#define ID_ID_KEY_CONFIG                32782
#define ID_MEET_SYS                     32783
#define ID_KEY_QUERY                    32783
#define ID_ID_KEY_QUERY                 32783
#define ID_AUTH_CONFIG                  32784
#define ID_ID_AUTH_CONFIG               32784
#define ID_STOP                         32785
#define ID_START                        32786
#define ID_ADD                          32787
#define ID_MODIFY                       32788
#define ID_DEL                          32789
#define ID_INTENTION_ADD                32791
#define ID_INTENTION_DEL                32792
#define ID_ADD_STRATEGY                 32793
#define ID_EXCHANGE_RATE_CONFIG         32794
#define ID_MENUITEM_AUTH                32795
#define ID_MENUITEM_LOCK                32797
#define ID_32798                        32798
#define ID_SUGUA                        32799
#define ID_SUGAR                        32800
#define ID__32801                       32801
#define ID_DATA_CURVE                   32802
#define ID__32803                       32803
#define ID_32804                        32804
#define ID_BOHAI                        32805
#define ID_32806                        32806
#define ID_StartBoHai                   32807
#define ID_BOHAI2                       32808
#define ID_32809                        32809
#define ID_PAUSEBOHAI                   32810
#define ID_BOHAI3                       32811

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        210
#define _APS_NEXT_COMMAND_VALUE         32812
#define _APS_NEXT_CONTROL_VALUE         1077
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
